spring:
  security:
    user:
      name: Andrew
      password: 12345
  datasource:
    # todo поднять бд в докере
    url: jdbc:postgresql://localhost:5432/filebase
    username: postgres
    password: Nevslomat16

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      max-file-size:
        15MB
  flyway:
    locations: src/main/resources/db/migration/
    user: postgres
    password: Nevslomat16
    enabled: false




upload:
  path: C:/Users/karimullin-ai/uploads