spring:
  security:
    user:
      name: Andrew
      password: 12345
  datasource:
    url: jdbc:postgresql://localhost:5432/filebase
    username: postgres
    password: Nevslomat16
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  servlet:
    multipart:
      max-file-size:
        15MB

upload:
  path: C:/Users/karimullin-ai/uploads