spring:
  security:
    user:
      name: Andrew
      password: 12345
  datasource:
    # todo поднять бд в докере*
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: mysecretpassword

  mail:
    username: bolshakofw@gmail.com
    password: ogxjljvnoceotctv
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size:
        15MB

upload:
  path: C:/Users/karimullin-ai/uploads